---
spring:
  batch:
    job:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kabuplus?useJDBCComplaintTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&character_set_server=utf8&characterEncoding=utf8
    initialization-mode: always
    username: fooqoo
    password: passw0rd
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: kabuplus

extension:
  api:
    kabu-plus:
      base-url: http://localhost:3000
      path: /
      connect-timeout: 1000
      read-timeout: 1000
      username: username
      password: password
