name: Google Functions

on:
  push:
    branches:
      - feature/#4-add-cicd-test-cicd

env:
  FUNCTION_ENV: ${{ secrets.FUNCTION_ENV }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_PROJECT_ID: ${{ secrets.GCP_SA_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests=true
          rm target/stock-crawler-*-SNAPSHOT.jar

      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: deploy
        run: |
          echo $FUNCTION_ENV | base64 -d > env.yaml
          echo $GCP_SA_KEY | base64 -d > src/resources/credential.json
          gcloud functions deploy stock-crawler --project $GCP_SA_PROJECT_ID --quiet --entry-point=org.springframework.cloud.function.adapter.gcp.GcfJarLauncher --trigger-topic=stock --env-vars-file=env.yaml --source=src --runtime=java11 --memory=512MB --vpc-connector=function2sql --timeout=300